repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
      # isort
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, "--select=I001,F401"]
      # bandit
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --select=S301, --exclude=tests*]
      # black
      - id: ruff-format
        types_or: [python, pyi, jupyter]
