name: Sync Main to Develop

on:
  push:
    branches:
      - main

jobs:
  sync-to-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Configure git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Switch to develop branch
        run: git checkout develop

      - name: Merge main into develop
        run: git merge main

      - name: Push changes to develop
        run: git push origin develop
